# Generated by Django 5.1 on 2024-08-31 15:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=7)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
