# Generated by Django 5.1 on 2024-08-31 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('topics', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=7)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Author')),
            ],
        ),
    ]
