# Generated by Django 5.1 on 2024-08-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_id_event_eventid_event_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='topics',
        ),
    ]
