# Generated by Django 5.1 on 2024-08-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventId',
            new_name='id',
        ),
    ]
