# Generated by Django 5.1 on 2024-09-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='authorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chatId',
            new_name='chat',
        ),
    ]
