# Generated by Django 5.1 on 2024-12-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Business', 'Business'), ('Education', 'Education'), ('Health', 'Health'), ('Music', 'Music'), ('Sports', 'Sports'), ('Arts', 'Arts'), ('Food', 'Food'), ('Technology', 'Technology'), ('Charity', 'Charity'), ('Travel', 'Travel'), ('Community', 'Community'), ('Career', 'Career'), ('Personal', 'Personal'), ('Film', 'Film'), ('Environment', 'Environment'), ('Gaming', 'Gaming'), ('Fashion', 'Fashion'), ('History', 'History'), ('Science', 'Science'), ('Language', 'Language')], max_length=100),
        ),
    ]
