# Generated by Django 5.1 on 2024-08-31 09:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authorId1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user1', to='users.user')),
                ('authorId2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user2', to='users.user')),
            ],
        ),
    ]
