# Generated by Django 5.1 on 2024-08-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chatId',
            new_name='id',
        ),
    ]
