# Generated by Django 5.1 on 2024-09-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
